import React from 'react'
import Head from 'next/head'
import Header from '../header/header.component'
import Footer from '../footer/footer.component'
import styles from './layout.module.scss'
import { useRouter } from 'next/router';

export default function Layout(props){

    const {
        pathname
      } = useRouter();
    
    const isIndexPage = pathname=='/'? true:false;

    return(
        <div className={styles['main-container']}>
            <Head>
                <title>Artom</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            {isIndexPage? <div className={styles['background-top-cover']}></div> : null} {/* to add a padding-top to background */}
            <Header />
            <div className={styles['body']}>
                {props.children}
            </div>
            <Footer />
        </div>
    )
}