import React from 'react'
import Head from 'next/head'
import styles from '../styles/Home.module.scss'
import HomePageAnim from '../components/home-page-anim/home-page-anim.component'
import HowItWorksCards from '../components/how-it-works-cards/how-it-works-cards.component'

/* redux */
import { connect } from 'react-redux';
import { createStructuredSelector } from 'reselect';
import { selectScrollToSectionFunction } from '../redux/homepage-handler/homepage-handler.selectors';
import { setScrollToSectionFunction } from '../redux/homepage-handler/homepage-handler.actions';

class Home extends React.Component {
  constructor(props){
    super(props);
    this.section1 = React.createRef()
    this.section2 = React.createRef()
    this.section3 = React.createRef()
    this.section4 = React.createRef()
    this.state={
      componentIsMount: false
    }
  }
  async componentDidMount(){
    this.props.setScrollToSectionFunction(this.scrollToSection)
    setTimeout(()=>{
      this.setState({componentIsMount:true})
    }, 500)
  }

  scrollToSection = (section)=>{
    var sectionRef
    switch(section) {
      case 'about-us':
        sectionRef = this.section1
        break
      case 'how-it-works':
        sectionRef = this.section2
        break
      case 'faq':
        sectionRef = this.section3
        break;
      default:
        sectionRef = this.section4
        break
    }
    sectionRef.current.scrollIntoView({behavior: 'smooth'})
  }

  render(){
    return (
      <div className={styles.container}>
        <Head>
          <title>Artom</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
        {this.state.componentIsMount ?
        <div>
          <HomePageAnim/>
          <div className={styles['sections-container']}>
            <section className={`${styles['section']} ${styles['about-us']}`}>
              <div className={styles['section-scrolling-anchor']} ref={this.section1}></div>

              <div className={styles['about-us-content-container']}>
                <div className={styles['about-us-title-and-text-container']}>
                  <h1 className={`${styles['section-title']} ${styles['about-us-title']}`} >A DIVERSIFIED PORTFOLIO</h1>
                  <p>
                    artom.io is a unique platform that enables you to buy and sell shares of iconic artworks using the blockchain technology.
                  </p>
                  <p>
                    Members of the community can build a diversified portfolio of iconic artworks curated by our industry-leading research team.
                  </p>
                </div>
                <div className={styles['about-us-illustration']}>ILLUSTRATION</div>
              </div>
            </section>
            <section className={`${styles['section']} ${styles['how-it-works']}`}>
              <div className={styles['section-scrolling-anchor']} ref={this.section2}></div>
              <h1 className={`${styles['section-title']} ${styles['how-it-works-title']}`}>HOW DOES IT WORKS</h1>
              <HowItWorksCards/>
            </section>
            <section className={`${styles['section']} ${styles['faq']}`}>
              <div className={styles['section-scrolling-anchor']} ref={this.section3}></div>
              <h1 className={`${styles['section-title']} ${styles['faq-title']}`} >FAQ</h1>
            </section>
            <section className={`${styles['section']} ${styles['stay-in-touch']}`}>
              <div className={styles['section-scrolling-anchor']} ref={this.section4}></div>
              <h1 className={`${styles['section-title']} ${styles['stay-in-touch-title']}`} >STAY IN TOUCH</h1>
              <div>Email address:</div>
              <input type='text' className={styles['stay-in-touch-email-input']}/>
            </section>
          </div>
        </div>:null}


      </div>
    )
  }
}

const mapStateToProps = createStructuredSelector({
  scrollToSectionFunction: selectScrollToSectionFunction,
});

const mapDispatchToProps = dispatch =>({
  setScrollToSectionFunction : scrollToSectionFunction => dispatch(setScrollToSectionFunction(scrollToSectionFunction))
});

export default connect(mapStateToProps, mapDispatchToProps)(Home);


/*export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to <a href="https://nextjs.org">Next.js!</a>
        </h1>

        <p className={styles.description}>
          Get started by editing{' '}
          <code className={styles.code}>pages/index.js</code>
        </p>

        <div className={styles.grid}>
          <a href="https://nextjs.org/docs" className={styles.card}>
            <h2>Documentation &rarr;</h2>
            <p>Find in-depth information about Next.js features and API.</p>
          </a>

          <a href="https://nextjs.org/learn" className={styles.card}>
            <h2>Learn &rarr;</h2>
            <p>Learn about Next.js in an interactive course with quizzes!</p>
          </a>

          <a
            href="https://github.com/vercel/next.js/tree/canary/examples"
            className={styles.card}
          >
            <h2>Examples &rarr;</h2>
            <p>Discover and deploy boilerplate example Next.js projects.</p>
          </a>

          <a
            href="https://vercel.com/new?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
            className={styles.card}
          >
            <h2>Deploy &rarr;</h2>
            <p>
              Instantly deploy your Next.js site to a public URL with Vercel.
            </p>
          </a>
        </div>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}*/
