import React from 'react'
import Head from 'next/head'
import styles from '../styles/Home.module.scss'
import HomePageAnim from '../components/home-page-anim/home-page-anim.component'
import HowItWorksCards from '../components/how-it-works-cards/how-it-works-cards.component'
import Image from 'next/image'

/* redux */
import { connect } from 'react-redux';
import { createStructuredSelector } from 'reselect';
import { selectScrollToSectionFunction } from '../redux/homepage-handler/homepage-handler.selectors';
import { setScrollToSectionFunction } from '../redux/homepage-handler/homepage-handler.actions';
import { setSelectedNavButton } from '../redux/nav-bar/nav-bar.actions';

class Home extends React.Component {
  constructor(props){
    super(props);
    this.section1 = React.createRef()
    this.section2 = React.createRef()
    this.section3 = React.createRef()
    this.section4 = React.createRef()
  }
  async componentDidMount(){
    this.props.setScrollToSectionFunction(this.scrollToSection)
  }

  scrollToSection = (section)=>{
    var sectionRef
    switch(section) {
      case 'about-us':
        sectionRef = this.section1
        break
      case 'how-it-works':
        sectionRef = this.section2
        break
      case 'faq':
        sectionRef = this.section3
        break;
      case 'stay-in-touch':
        sectionRef = this.section3
        break;
      default:
        sectionRef = this.section4
        break
    }
    sectionRef.current.scrollIntoView({behavior: 'smooth'})
  }

  scrollTo = (section)=>{
    if(this.props.scrollToSectionFunction !== 'undefined'){
        this.props.scrollToSectionFunction(section);
        this.props.setSelectedNavButton(section)
    }
  }
  render(){
    return (
      <div className={styles.container}>
        <Head>
          <title>Artom</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
        <HomePageAnim/>
        <div className={styles['sections-container']}>
        <section className={`${styles['section']} ${styles['about-us']}`}>
          <div className={styles['section-scrolling-anchor']} ref={this.section1}></div>

          <div className={styles['about-us-content-container']}>
            <div className={styles['about-us-title-and-text-container']}>
              <h1 className={`${styles['section-title']} ${styles['about-us-title']}`} >A DIVERSIFIED PORTFOLIO</h1>
              <p>
                artom.io is a unique platform that enables you to buy and sell shares of iconic artworks using the blockchain technology.
              </p>
              <p>
                Members of the community can build a diversified portfolio of iconic artworks curated by our industry-leading research team.
              </p>
            </div>
            <div className={styles['about-us-illustration']}>ILLUSTRATION</div>
          </div>
        </section>
        <section className={`${styles['section']} ${styles['how-it-works']}`}>
          <div className={styles['section-scrolling-anchor']} ref={this.section2}></div>
          <h1 className={`${styles['section-title']} ${styles['how-it-works-title']}`}>HOW DOES IT WORKS</h1>
          <HowItWorksCards/>
        </section>
        <section className={`${styles['section']} ${styles['faq']}`}>
          <div className={styles['section-scrolling-anchor']} ref={this.section3}></div>
          <h1 className={`${styles['section-title']} ${styles['faq-title']}`} >FAQ</h1>
        </section>
        <section className={`${styles['section']} ${styles['stay-in-touch']}`}>
          <div className={styles['section-scrolling-anchor']} ref={this.section4}></div>
          <h1 className={`${styles['section-title']} ${styles['stay-in-touch-title']}`} >STAY IN TOUCH</h1>
          <p>Want to know more about the project, leave us your contact details and we will get back to you soon</p>
          <div className={styles['email-input-container']}>
            <input type='text' className={styles['stay-in-touch-email-input']} placeholder='Email...'/>
            <button>Ok</button>
          </div>
          <div className={styles['social-network-buttons-container']}>
            <div className={styles['social-network-logo']}>
              <Image src='/facebook-logo.png' alt='facebook-logo' layout={'fill'} objectFit={'contain'}/>
            </div>
            <div className={styles['social-network-logo']}>
              <Image src='/twitter-logo.png' alt='twitter-logo' layout={'fill'} objectFit={'contain'}/>
            </div>
            <div className={styles['social-network-logo']}>
              <Image src='/instagram-logo.jpg' alt='instagram-logo' layout={'fill'} objectFit={'contain'}/>
            </div>
          </div>
        </section>
      </div>
      <footer className={styles.footer}>
        <div className={styles['footer-block-1']}>
          <div className={styles['artom-logo-container']}>
            <div className={styles['artom-logo']} onClick={()=> this.scrollTo('about-us')}>
              <img className={styles['artom-logo']} src='/artom-logo.png' alt='artom-logo' layout={'fill'} objectFit={'contain'}/>
            </div>
          </div>
          <div className={styles['footer-block-1-child-container']}>
            <ul>
              <li><span onClick={()=> this.scrollTo('about-us')}>Home</span></li>
              <li><span onClick={()=> this.scrollTo('about-us')}>About Us</span></li>
              <li><span onClick={()=> this.scrollTo('how-it-works')}>How it Works</span></li>
              <li><span onClick={()=> this.scrollTo('faq')}>FAQ</span></li>
              <li><span onClick={()=> this.scrollTo('stay-in-touch')}>Stay in Touch</span></li>
            </ul>
          </div>
          <div className={styles['footer-block-1-child-container']}>
            <div><span>White Paper</span></div>
          </div>
          <div className={styles['footer-block-1-child-container']}>
            <a className={styles['artom-email']}><span>hello@artom.io</span></a>
          </div>
        </div>
        <div className={styles['footer-block-2']}>
          <div><span>Terms & Conditions</span></div>
          <div><span>Privacy Policy</span></div>
          <div><span>artom.io &#169; 2022</span></div>
        </div>
      </footer>
    </div>
    )
  }
}

const mapStateToProps = createStructuredSelector({
  scrollToSectionFunction: selectScrollToSectionFunction,
});

const mapDispatchToProps = dispatch =>({
  setScrollToSectionFunction : scrollToSectionFunction => dispatch(setScrollToSectionFunction(scrollToSectionFunction)),
  setSelectedNavButton : navButtonName => dispatch(setSelectedNavButton(navButtonName)) 
});

export default connect(mapStateToProps, mapDispatchToProps)(Home);


/*export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to <a href="https://nextjs.org">Next.js!</a>
        </h1>

        <p className={styles.description}>
          Get started by editing{' '}
          <code className={styles.code}>pages/index.js</code>
        </p>

        <div className={styles.grid}>
          <a href="https://nextjs.org/docs" className={styles.card}>
            <h2>Documentation &rarr;</h2>
            <p>Find in-depth information about Next.js features and API.</p>
          </a>

          <a href="https://nextjs.org/learn" className={styles.card}>
            <h2>Learn &rarr;</h2>
            <p>Learn about Next.js in an interactive course with quizzes!</p>
          </a>

          <a
            href="https://github.com/vercel/next.js/tree/canary/examples"
            className={styles.card}
          >
            <h2>Examples &rarr;</h2>
            <p>Discover and deploy boilerplate example Next.js projects.</p>
          </a>

          <a
            href="https://vercel.com/new?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
            className={styles.card}
          >
            <h2>Deploy &rarr;</h2>
            <p>
              Instantly deploy your Next.js site to a public URL with Vercel.
            </p>
          </a>
        </div>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}*/
